### ISSUE TITLE
Mirror to jCenter

### ISSUE THREAD

**Issue by snorkel123** [dmstocking/support-optional#1]
When bundling your backport with other library, sticking to Maven Central/jCenter means that you need to ask user not only to include jCenter to repo list, but jitpack as well.

**Comment by dmstocking** [comment]
I haven't put anything on jCenter, but I will see how hard that is. Should be easy. I would think/hope so.

**Comment by snorkel123** [comment]
@dmstocking It is indeed really easy. I did this couple of days before. You will just need to wait day or two before they approve your package.

I have done it via [Bintray Gradle Plugin](https://github.com/bintray/gradle-bintray-plugin), publishing via `bintrayUpload` task

Barebones `gradle.build` script:

```
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    id "com.jfrog.bintray" version "1.7.3"
}

group 'your.group'
version 'a.b.c'

apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'maven-publish'

sourceCompatibility = 1.7

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId 'your.group'
            artifactId 'your-artifact'
            version 'a.b.c'
        }
    }
}

bintray {
    user = System.getenv('BINTRAY_USER')
    key = System.getenv('BINTRAY_API_KEY')
    publications = ['mavenJava']

    dryRun = false
    publish = true
    override = true
    pkg {
        repo = 'YourGreatRepo'
        name = 'your-artifact'
        version {
            name = 'a.b.c'
            released = new Date()
        }
    }
}

```

**Comment by dmstocking** [comment]
I think I have done the necessary work for it to be added to jcenter. Guess we will wait and see. I was displeased I couldn't choose a username when I signed up via my google lol. Whatever I guess https://bintray.com/buttink/support-optional/support-optional

**Comment by snorkel123** [comment]
@dmstocking I tried to  `compile 'com.github.dmstocking:support-optional:1.1'`, but in IntelliJ's Gradle view under project dependencies list I see `support-optional-1.1.jar-com.github.dmstocking:support-optional:1.1` instead of regular `com.github.dmstocking:support-optional:1.1`

**Comment by dmstocking** [comment]
So bintray sent me an email and I need to also include a pom file to get included to jcenter. So I am going to figure out whatever I need to do (or probably fix) to get that included. This is the change set if anyone is interested https://github.com/dmstocking/support-optional/commit/c548bfbcfc3b4fcf4178db709b92200ab43f9111

**Comment by snorkel123** [comment]
@dmstocking in my case `pom.xml` was included by default

**Comment by dmstocking** [comment]
For anyone watching, I am still trying to get this done. I have just been busy with work, taxes, fixing my car, fixing my house, not going insane :)

**Comment by 4brunu** [comment]
First of all, thanks for this library :) Any news on this?

**Comment by dmstocking** [comment]
So I figured out how to do the sources.jar and then made a version 1.2 (because I totally forgot about this and can't edit 1.1 because it's 180 days old. I am waiting to hear back about being added to JCenter.

**Comment by dmstocking** [comment]
Pushed the code to include the *-sources.jar. Going to wait before tagging the commit as release 1.2 just in case I have to change something else for JCenter. Sorry I took so long for this. I am happy you actually use the library though. :smiley:

**Comment by 4brunu** [comment]
Cool, thanks, please let me know when it's solved :) Also I really like the concept of being easy to replace with the Java8 Optional 👍

**Comment by dmstocking** [comment]
I was able to successfully add this to another project without jitpack! I am going to close this issue for now. I only am on JCenter should I also mirror to maven central?

**Comment by snorkel123** [comment]
Thanks for pushing it to jcenter!

I think jcenter is ok for now.

15 нояб. 2017 г. 6:32 PM пользователь "David Stocking" <
notifications@github.com> написал:
